# Generated by Django 5.0 on 2026-03-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amountPurchased',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
