# Generated by Django 5.0 on 2026-03-04 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_review_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='commentCounter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Most',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewCounter', models.PositiveIntegerField(default=0)),
                ('amountPurchased', models.PositiveIntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
